# Generated by Django 6.0.3 on 2026-04-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(choices=[('BCT', 'BCT'), ('BEI', 'BEI'), ('BCE', 'BCE'), ('BME', 'BME')], max_length=3, unique=True),
        ),
    ]
