# Generated by Django 6.0.3 on 2026-04-05 04:00

from django.db import migrations


def seed_departments(apps, schema_editor):
    Department = apps.get_model("learning_hub", "Department")
    defaults = [
        ("BCT", "Computer Engineering"),
        ("BEI", "Electronics and Information Engineering"),
        ("BCE", "Civil Engineering"),
        ("BME", "Mechanical Engineering"),
    ]

    for code, name in defaults:
        Department.objects.update_or_create(code=code, defaults={"name": name})


def reverse_seed_departments(apps, schema_editor):
    Department = apps.get_model("learning_hub", "Department")
    Department.objects.filter(code__in=["BCT", "BEI", "BCE", "BME"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_hub", "0002_alter_department_code"),
    ]

    operations = [
        migrations.RunPython(seed_departments, reverse_seed_departments),
    ]
